apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ "oldxu.net" | b64enc }}
  MYSQL_DATABASE: {{ "helm" | b64enc }}
---
{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
data:
  tls.crt: {{ .Files.Get "ssl/server.crt" | b64enc }}
  tls.key: {{ .Files.Get "ssl/server.key" | b64enc }}
{{- end }}